### ISSUE TITLE
Invoice overview shows same sum values for different clients

### ISSUE THREAD

**Issue by lwndp** [LiaraAlis/kimai2-SmallBusinessRuleBundle#5]
As initially outlined here: https://github.com/kevinpapst/kimai2/issues/3562

Issue resolved when deactivating the plugin entirely (not just the 'small business' option in settings

**Comment by LiaraAlis** [comment]
This is already fixed in v1.0.1. Please update.

**Comment by lwndp** [comment]
Awesome! Thank you!

**Comment by LiaraAlis** [comment]
Thank you for using my plugin. I appreciate any feedback. 😊

**Comment by lwndp** [comment]
The invoice preview, overview section (at the bottom), still doesn't seem to show correct projects and related total hours. Only the total sum is now correct per client. Can you confirm this on your end?

I think this issue should be opened again.

**Comment by LiaraAlis** [comment]
You're totally right, I didn't noticed that the listed projects doesn't match the customer.
This is a very strange problem. I have a look on this.

**Comment by LiaraAlis** [comment]
@lwndp Can you please try to checkout the master branch and test my changes in commit https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/commit/c36368305b02dcd526b4ae89e4502b3407770982?
I hope that these changes fixes the problem. To be honest, I have not yet really understood the cause of this issue…

If everything works well, I will release a new version.

**Comment by lwndp** [comment]
@LiaraAlis your fix seems to have resolved the issue. Only thing I'd like to note is that the directory containing your plugin is called kimai2-SmallBusinessBundle and thus doesn't load into the kimai cache. I guess there is some sort of name validation going on. I had to rename it to "SmallBusinessBundle" for it to show up / work.

**Comment by LiaraAlis** [comment]
@lwndp This is because this repository is named "kimai2-SmallBusinessRuleBundle". Because of that, you have to specify the target directory when using `git clone`. See here: https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle#installation

**Comment by LiaraAlis** [comment]
Released v1.0.2: https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/releases/tag/v1.0.2

**Comment by lwndp** [comment]
My bad, sorry for not reading all the was to the right 😅
Thanks for the quick response and fix 🙏
